### ISSUE TITLE
How to send nack back to a queue

### ISSUE THREAD

**Issue by kevinblade** [richthegeek/beatrix#6]
hi!

I want to send nack message to reject and requeue a message i some cases.
How to do that with your beatrix package ?

Thank you.

**Comment by richthegeek** [comment]
Hi Kevin,

This library isn't really updated anymore as I wrote it two jobs ago. But if it helps you, use it :)

Beatrix tries to hide the details of AMQP so a job can fail by either throwing an error or explicitly calling reject:
```javascript
process: (message) => {
  if (message.body.foo !== 'bar'){
    message.reject("Foo is not bar");
  }

  assert.strictEqual(message.body.foo, 'bar');

  message.body.foo.bar.baz // will throw because  the path doesnt exist
}
```

All 3 are valid ways to reject (nack) a message. Requeueing is then handled by the queue or job's retry configuration (

Ref: https://github.com/richthegeek/beatrix/blob/master/src/job.js#L235
Ref: https://github.com/richthegeek/beatrix/blob/master/test/retry.js#L52

Sorry this isn't documented better!

**Comment by kevinblade** [comment]
Thank you Richard.
I understood very well,

**Comment by richthegeek** [comment]
@kevinblade good :)

I published a new version with updated dependencies, there were some audit issues.
